version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Adjust based on frontend framework
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm start

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: python app.py  # Or: gunicorn main:app --bind 0.0.0.0:8000

